### ISSUE TITLE
Use fieldsets to define sections in a form

### ISSUE THREAD

**Issue by joostf** [ColinDorr/minor-tauw-sensoren#26]
https://github.com/ColinDorr/minor-tauw-sensoren/blob/68547bd2c603d00a8d691d58e0af8202016713ed/TauwApp/views/form.ejs#L23

**Comment by ColinDorr** [comment]
The cms is changed and now uses fieldsets instead of sectios or divs. 

I have also made the following changes to the CMS: (#63)
- changed the styling of the CMS.
- changed the UI to make it easyer to use.
- have added a serverside validation, that checks if all the required fields were filled in.
