### ISSUE TITLE
Remove Greensock

### ISSUE THREAD

**Issue by ColinDorr** [ColinDorr/minor-tauw-sensoren#59]
Greensock is not nessesary, for those small animations. You can do it with just css animations.

**Comment by jaimiederijk** [comment]
You can't animate svg with css outside Chrome. [I tried !] (https://github.com/ColinDorr/minor-tauw-sensoren/blob/feat/animation2/jaimie/TauwApp/public/stylesheets/_animations.scss) So were keeping greensock in.
