### ISSUE TITLE
Map on mobile fullscreen

### ISSUE THREAD

**Issue by nooroel-imamdi** [ColinDorr/minor-tauw-sensoren#71]
According to the teachers, we can put the map full screen instead scrolling horizontally.

**Comment by jaimiederijk** [comment]
Sections are variable in length. On my mobile phone the middle section is one finger width wide, any smaller than that and seems to me that it would become a problem. And Tauw would probably like to expand/change the current map so it is uncertain whether it would fit in the future. 

If the map is shown full screen we should at least make sure it can zoom in.

**Comment by jaimiederijk** [comment]
It has been done
